name: dev DAB

on:
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Databricks CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

    - name: Deploy to dev
      run: databricks bundle destroy --auto-approve --force
      env:
        DATABRICKS_HOST: ${{secrets.DATABRICKS_HOST}}
        DATABRICKS_TOKEN: ${{secrets.DATABRICKS_TOKEN}}

    - name: Deploy to dev
      run: databricks bundle deploy
      env:
        DATABRICKS_HOST: ${{secrets.DATABRICKS_HOST}}
        DATABRICKS_TOKEN: ${{secrets.DATABRICKS_TOKEN}}
          
    - name: Run pipeline
      run: databricks bundle run etl-dlt-sensors-pipeline
      env:
        DATABRICKS_HOST: ${{secrets.DATABRICKS_HOST}}
        DATABRICKS_TOKEN: ${{secrets.DATABRICKS_TOKEN}}