name: prod DAB

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Databricks CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

    - name: Validate bundle yml
      run: databricks bundle validate
      env:
        DATABRICKS_HOST: ${{secrets.DATABRICKS_HOST}}
        DATABRICKS_TOKEN: ${{secrets.DATABRICKS_TOKEN}}

    - name: Run unit tests
      if: success()
      run: pytest tests
      env:
        DATABRICKS_HOST: ${{secrets.DATABRICKS_HOST}}
        DATABRICKS_TOKEN: ${{secrets.DATABRICKS_TOKEN}}

    - name: Destroy past bundle files
      continue-on-error: true
      run: databricks bundle destroy -e prod --auto-approve --force-lock
      env:
        DATABRICKS_HOST: ${{secrets.DATABRICKS_HOST}}
        DATABRICKS_TOKEN: ${{secrets.DATABRICKS_TOKEN}}

    - name: Deploy bundle
      run: databricks bundle deploy -e prod
      env:
        DATABRICKS_HOST: ${{secrets.DATABRICKS_HOST}}
        DATABRICKS_TOKEN: ${{secrets.DATABRICKS_TOKEN}}
          
    - name: Run pipeline
      if: success()    
      run: databricks bundle run -e prod etl-dlt-sensors-pipeline 
      env:
        DATABRICKS_HOST: ${{secrets.DATABRICKS_HOST}}
        DATABRICKS_TOKEN: ${{secrets.DATABRICKS_TOKEN}}
    


    